const sampleListings = [
  {
    title: "Taj Mahal, Agra",
    description: "One of the Seven Wonders of the World, a symbol of eternal love. This magnificent ivory-white marble mausoleum on the right bank of the river Yamuna in Agra, India is a must-visit.",
    image: {
      filename: "tajmahal",
      url: "https://th.bing.com/th/id/OIP.WXSkN9Hs0zF6sdwz5pnL5AHaEK?w=293&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    },
    price: 1500,
    location: "Agra, Uttar Pradesh",
    country: "India",
    category: "Historical",
    geometry: { type: "Point", coordinates: [78.0421, 27.1751] },
  },
  {
    title: "Amer Fort, Jaipur",
    description: "Amer Fort is known for its artistic Hindu style elements. With its large ramparts and series of gates and cobbled paths, the fort overlooks Maota Lake.",
    image: {
      filename: "jaipur",
      url: "https://th.bing.com/th/id/OIP.Z_ByE1kiVHgMJxZwjuaw0AHaES?w=288&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    },
    price: 2500,
    location: "Jaipur, Rajasthan",
    country: "India",
    category: "Historical",
    geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
  },
  {
    title: "Tea Gardens, Munnar",
    description: "Breathtaking hill station famous for its tea plantations and rolling hills. Munnar is a town in the Western Ghats mountain range in India's Kerala state.",
    image: {
      filename: "munnar",
      url: "https://th.bing.com/th/id/OIP.8N9h8u9hPZeFmCU0f782-wHaEe?w=243&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    },
    price: 3200,
    location: "Munnar, Kerala",
    country: "India",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [77.0595, 10.0889] },
  },
  {
    title: "Ganga Ghats, Varanasi",
    description: "One of the oldest living cities in the world, a spiritual hub on the banks of Ganga. Varanasi is a city in the northern Indian state of Uttar Pradesh.",
    image: {
      filename: "varanasi",
      url: "https://media.istockphoto.com/id/840280150/photo/boats-at-river-ganga-and-people-at-holy-ghats-among-ancient-hindu-temples.jpg?s=612x612&w=0&k=20&c=x6NT5yQCwLKMBwzBhUlI4pnqVi_9cDphAOS7FUZ_bC4=",
    },
    price: 1200,
    location: "Varanasi, Uttar Pradesh",
    country: "India",
    category: "Historical",
    geometry: { type: "Point", coordinates: [82.9739, 25.3176] },
  },
  {
    title: "Baga Beach, Goa",
    description: "Tropical paradise known for its pristine beaches, vibrant nightlife, and Portuguese heritage. Baga is a seaside town in Bardez, Goa, North Goa district.",
    image: {
      filename: "goa",
      url: "https://www.tourmyindia.com/blog/wp-content/uploads/2021/05/Patnem-Goa.jpg",
    },
    price: 4500,
    location: "North Goa, Goa",
    country: "India",
    category: "Beach",
    geometry: { type: "Point", coordinates: [73.8125, 15.5204] },
  },
  {
    title: "Pangong Lake, Leh",
    description: "High-altitude desert with stunning landscapes, monasteries, and crystal clear lakes. Pangong Tso is an endorheic lake in the Himalayas.",
    image: {
      filename: "ladakh",
      url: "https://static.toiimg.com/photo/msid-79549873,width-96,height-65.cms",
    },
    price: 5000,
    location: "Leh, Ladakh",
    country: "India",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [77.5771, 34.1526] },
  },
  {
    title: "The Lake Palace, Udaipur",
    description: "The City of Lakes, famous for its romantic palaces and boat rides. Lake Palace is a former summer palace of the royal family of Mewar.",
    image: {
      filename: "udaipur",
      url: "https://tse2.mm.bing.net/th/id/OIP.WkZ5pOkQs88FSE_BgnP3GwHaEw?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    price: 3800,
    location: "Udaipur, Rajasthan",
    country: "India",
    category: "Luxury",
    geometry: { type: "Point", coordinates: [73.6824, 24.5854] },
  },
  {
    title: "Virupaksha Temple, Hampi",
    description: "UNESCO World Heritage site featuring ruins of the Vijayanagara Empire amidst rocky landscapes. It is located in Hampi in the Vijayanagara district of Karnataka.",
    image: {
      filename: "hampi",
      url: "https://edge.ixigo.com/ixi-api/img/511a1afde4b015f836876ac5_600x315.jpg",
    },
    price: 1800,
    location: "Hampi, Karnataka",
    country: "India",
    category: "Historical",
    geometry: { type: "Point", coordinates: [76.4600, 15.3350] },
  },
  {
    title: "Lakshman Jhula, Rishikesh",
    description: "The Yoga Capital of the World, known for adventure activities and Ganga Aarti. It is a suspension bridge across the river Ganges.",
    image: {
      filename: "rishikesh",
      url: "https://indiano.travel/wp-content/uploads/2022/06/Beautiful-Ram-Jhula-Bridge-and-Ganga-river-taken-in-Rishikesh-India.jpg",
    },
    price: 1500,
    location: "Rishikesh, Uttarakhand",
    country: "India",
    category: "Camping",
    geometry: { type: "Point", coordinates: [78.2676, 30.0869] },
  },
  {
    title: "Backwaters Houseboat, Alleppey",
    description: "Venice of the East, famous for its backwaters and houseboat stays. Alappuzha is a city on the Laccadive Sea in the southern Indian state of Kerala.",
    image: {
      filename: "alleppey",
      url: "https://www.tripsavvy.com/thmb/eCWPvoGI5N6yIlOmwSpwFueeChU=/2120x1414/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-491280712-1cdfa38202154daa9bb4075d8c54c67f.jpg",
    },
    price: 4000,
    location: "Alleppey, Kerala",
    country: "India",
    category: "Other",
    geometry: { type: "Point", coordinates: [76.3388, 9.4981] },
  },
  {
    title: "Mall Road, Shimla",
    description: "Queen of Hills, a popular colonial-era hill station with scenic views. The Mall Road is the main street in Shimla, Himachal Pradesh.",
    image: {
      filename: "shimla",
      url: "https://eindiatourism.in/wp-content/uploads/2023/07/Mall_Road_Shimla_1.jpg",
    },
    price: 2800,
    location: "Shimla, Himachal Pradesh",
    country: "India",
    category: "Arctic",
    geometry: { type: "Point", coordinates: [77.1731, 31.1048] },
  },
  {
    title: "Golden Fort, Jaisalmer",
    description: "The Golden City, known for its massive fort and camel safaris in the Thar Desert. Jaisalmer is a city in the Indian state of Rajasthan.",
    image: {
      filename: "jaisalmer",
      url: "https://thumbs.dreamstime.com/b/jaisalmer-rajasthan-india-october-fort-sonar-quila-golden-living-made-yellow-sandstone-unesco-world-heritage-site-thar-245736217.jpg",
    },
    price: 2200,
    location: "Jaisalmer, Rajasthan",
    country: "India",
    category: "Historical",
    geometry: { type: "Point", coordinates: [70.9126, 26.9157] },
  },
  {
    title: "Rohtang Pass, Manali",
    description: "A gateway for skiing and trekking, surrounded by majestic snow-capped mountains. It is a high mountain pass on the eastern Pir Panjal Range of the Himalayas.",
    image: {
      filename: "manali",
      url: "https://tse3.mm.bing.net/th/id/OIP.u4U66aAHKtSHb7VchLRMTQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    price: 3000,
    location: "Manali, Himachal Pradesh",
    country: "India",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [77.1892, 32.2432] },
  },
  {
    title: "Tiger Hill, Darjeeling",
    description: "Famous for its tea gardens, views of Kanchenjunga, and the Himalayan Railway. Darjeeling is a town in the Indian state of West Bengal.",
    image: {
      filename: "darjeeling",
      url: "https://tse2.mm.bing.net/th/id/OIP.-8clbW2NnnbiIluth5nmWAHaEO?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    price: 2600,
    location: "Darjeeling, West Bengal",
    country: "India",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [88.2627, 27.0360] },
  },
  {
    title: "Gulmarg Gondola, Kashmir",
    description: "A premier ski destination known for its gondola rides and high ridges. Gulmarg is a town in the Baramulla district of Jammu and Kashmir.",
    image: {
      filename: "gulmarg",
      url: "https://tse1.mm.bing.net/th/id/OIP.IAbhgHSi1MwMDxv1ttjLtwHaEG?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    price: 5500,
    location: "Gulmarg, Jammu and Kashmir",
    country: "India",
    category: "Arctic",
    geometry: { type: "Point", coordinates: [74.3800, 34.0500] },
  },
];

module.exports = { data: sampleListings };
